stages:
   - build

build docker image:
   image: docker:20.10.5
   services:
      - docker:20.10.5-dind
   stage: build
   variables:
      #DOCKER_HOST: tcp://docker:2376
      #DOCKER_TLS_CERTDIR: "/certs"
      IMAGE: "$CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH"
   before_script:
      - docker login --username="$CI_REGISTRY_USER" --password="$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
      - docker pull "$IMAGE" || true
   script:
      - >-
         docker build
         --tag "$IMAGE"
         .
      - docker push "$IMAGE"
   tags:
      - ufsm-pnip


deploy docker image:
   stage: deploy
   variables:
      SERVICE_REQUESTED: FRONT
      COMMAND: deploy
      BRANCH_NAME: $CI_COMMIT_BRANCH
   trigger:
      project: pnip-mpa/infra/review-env-deployer
      strategy: depend
